CREATE TABLE user_info (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  user_password TEXT NOT NULL,
  brood_name TEXT,
  solar_day INTEGER
);