CREATE TABLE status_report (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brood_name TEXT NOT NULL,
  solar_day INTEGER,
  aliens INTEGER,
  spawning_cost INTEGER,
  structures INTEGER,
  biomass INTEGER,
  synapse INTEGER
);