CREATE TABLE status_report (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brood_name TEXT NOT NULL,
  solar_day INTEGER,
  aliens INTEGER,
  structures INTEGER,
  biomass INTEGER,
  synapse_required INTEGER,
  synapse_produced INTEGER
);