CREATE TABLE structures (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  -- buildable CHECK TRUE,
  structure_name TEXT NOT NULL,
  hp INTEGER,
  atk INTEGER NOT NULL,
  biomass_cost INTEGER NOT NULL,
  synapse_produced INTEGER,
  description TEXT,
  special_features TEXT
);