CREATE TABLE structures (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  structure_name TEXT NOT NULL,
  constructable BOOLEAN,
  constructing BOOLEAN,
  active BOOLEAN,
  to_construct INTEGER,
  constructing_count INTEGER,
  brood_count INTEGER,
  hp INTEGER,
  atk INTEGER NOT NULL,
  biomass_cost INTEGER NOT NULL,
  synapse_produced INTEGER,
  description TEXT,
  special_features TEXT
);