CREATE TABLE construction_order (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  structure_name TEXT NOT NULL,
  total_to_construct INTEGER,
  biomass_cost INTEGER,
  synapse_produced INTEGER
);