CREATE TABLE spawning_plans (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  to_spawn BOOLEAN,
  total_aliens_spawning INTEGER,
  total_biomass_cost INTEGER,
  total_synapse_required INTEGER
);